<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>放款审核-备注信息</title>
</head>
<body>
<?php if ($results == []){ ?>
<div>信息有误</div>
<?php }else{?>
    <?php foreach ($results as $result) {?>
        <div>操作员：<?= $result['name'] ?></div>
        <div>操作结果：<?= $result['result'] ?></div>
        <div>备注信息：<?= $result['remark'] ?></div>
        <br>
    <?php }?>
<?php }?>

</body>
</html>
