<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>my first page</h1>
        <form action="/q/test" method="post">
            <input type="text" name="csrf_name" value="<?php echo $csrf_name ?>" >
            <input type="text" name="csrf_value" value="<?php echo $csrf_value ?>" >
            <input type="submit" value="提交">
        </form>
    </body>
</html>
